"""empty message

Revision ID: 0a7483ce99e8
Revises: 8b558a9ae6de
Create Date: 2024-12-16 16:06:08.674874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7483ce99e8'
down_revision = '8b558a9ae6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userPhotoUrl', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userPhotoFile', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'userPhoto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userPhoto', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'userPhotoFile')
    op.drop_column('users', 'userPhotoUrl')
    # ### end Alembic commands ###
