"""empty message

Revision ID: 10c54e0cfd16
Revises: 0a7483ce99e8
Create Date: 2024-12-16 16:06:53.844140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c54e0cfd16'
down_revision = '0a7483ce99e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userPhoto', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'userPhotoUrl')
    op.drop_column('users', 'userPhotoFile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userPhotoFile', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('userPhotoUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'userPhoto')
    # ### end Alembic commands ###
