"""empty message

Revision ID: 8b558a9ae6de
Revises: d99962b519ad
Create Date: 2024-12-15 21:25:20.168814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b558a9ae6de'
down_revision = 'd99962b519ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photoType', sa.String(length=10), nullable=True))
    op.drop_column('users', 'phototype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phototype', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('users', 'photoType')
    # ### end Alembic commands ###
