"""empty message

Revision ID: d99962b519ad
Revises: f1e9161ac111
Create Date: 2024-12-15 20:47:32.066964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99962b519ad'
down_revision = 'f1e9161ac111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phototype', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phototype')
    # ### end Alembic commands ###
