"""Initial migration

Revision ID: f1e9161ac111
Revises: 7fc15c6407d5
Create Date: 2024-12-03 21:36:15.220209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e9161ac111'
down_revision = '7fc15c6407d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'dummy_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dummy_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
