"""empty message

Revision ID: 18bd3614021e
Revises: b779058089f5
Create Date: 2022-03-28 15:16:29.589038

"""
from alembic import op
import sqlalchemy as sa
# migration file

# ... other imports
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
# ...

# revision identifiers, used by Alembic.
revision = '18bd3614021e'
down_revision = 'b779058089f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userPhoto', sa.Text(), nullable=True))
    # ### end Alembic commands ###
        # ... logic to create tables

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        #  add an ALTER TABLE command here for each table created in the file


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userPhoto')
    # ### end Alembic commands ###
