"""empty message

Revision ID: 12e92541dd90
Revises: adb996523981
Create Date: 2022-02-05 12:17:23.059510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e92541dd90'
down_revision = 'adb996523981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('categoryId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'categories', ['categoryId'], ['id'])
    op.drop_column('projects', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'categoryId')
    op.drop_table('categories')
    # ### end Alembic commands ###
