"""empty message

Revision ID: 5aec2b50a422
Revises: 38b9034f4f3c
Create Date: 2022-02-07 10:42:54.387962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aec2b50a422'
down_revision = '38b9034f4f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('videoUrl', sa.Text(), nullable=True))
    op.drop_column('instructions', 'viedoUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('viedoUrl', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('instructions', 'videoUrl')
    # ### end Alembic commands ###
