"""empty message

Revision ID: b779058089f5
Revises: badceaabd9ea
Create Date: 2022-03-18 23:20:25.700115

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'b779058089f5'
down_revision = 'badceaabd9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.Text(), nullable=False))
    # ### end Alembic commands ###
        # ... logic to create tables

    if environment == "production":
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
        #  add an ALTER TABLE command here for each table created in the file


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
