"""empty message

Revision ID: e79672e5eb6b
Revises: d2360ebde7be
Create Date: 2022-06-23 20:16:10.916299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79672e5eb6b'
down_revision = 'd2360ebde7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('supply', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'supply')
    # ### end Alembic commands ###
